apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
        - name: frontend-react
          image: caravem/frontend-react:0a9dba27b0927ed4430a14532482928811600f5e
