apiVersion: v1
kind: Service
metadata:
  name: frontend-react-service
  namespace: develop
spec:
  selector:
    app: frontend-react
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
